### ISSUE TITLE
Unhandled Exception: FileSystemException: Cannot open file

### ISSUE THREAD

**Issue by satishkoladiya** [frencojobs/hls-downloader-flutter#1]
on ios it shows error while downloading. please help to resolve it.

[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: FileSystemException: Cannot open file, path = '/Users/satishkoladiya/Library/Developer/CoreSimulator/Devices/2CE75B60-F0CB-4273-A5BD-C3565AB9EE28/data/Containers/Data/Application/A5014365-F20B-472E-8039-6FFD1405CA5B/Documents/35257098/../video/180_250000/hls/segment_0.ts' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
#1      _rootRunUnary (dart:async/zone.dart:1192:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#8      _rootRun (dart:async/zone.dart:1184:13)

**Comment by frencojobs** [comment]
I think I forgot to add file creation after path creation in download function. It's kinda weird the error didn't appear on my machine.

Can you try again? The commit f1af5e55ee648ba1b948fc36b176f22cf8bcdcf3 probably should fix this.

**Comment by satishkoladiya** [comment]
Hey, Downloading is working. Now please help to play video. Its not playing after download.

**Comment by frencojobs** [comment]
Are you on running on a simulator? Because on iOS, the videos will only play on Actual Device but not on a simulator. It is a famously known bug by the Flutter's [video_player](https://pub.dev/packages/video_player) plugin.

**Comment by satishkoladiya** [comment]
No i''m running in iOD device

**Comment by satishkoladiya** [comment]
If you are available on skype please connect me, my skype id : satish.koladiya

**Comment by frencojobs** [comment]
Thank you mate, but I don't have a skype. We can talk here.

**Comment by satishkoladiya** [comment]
I'm running code on my iOS device. I'm downloading http://playertest.longtailvideo.com/adaptive/bipbop/bipbop.m3u8 link. After download its not playing only loader is showing. Please help to resolve this.

**Comment by frencojobs** [comment]
The video player is very simple here, I removed chewie before that because I thought it was the one causing the issue. So currently it's just a plain video player, no configurations added. If the file path is not the problem, there's no way the video player messed up as it's in the simplest possible form.

Do you have any logs? That video works just fine on Android.

**Comment by frencojobs** [comment]
It is possible that https://github.com/flutter/flutter/issues/48670 issue is the culprit. Maybe because the video_player of Flutter is currently under heavy development, there are lots of errors appearing here and there.
